//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Payoneer.Payoneer.Hotels.Model.HotelsDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBed
    {
        public int RoomId { get; set; }
        [Key]
        public int BedId { get; set; }
        public short BedType { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
