//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Payoneer.Payoneer.Hotels.Contracts
{ 
	public class HotelCI
	{
		public System.Int32 HotelId { get; set; }
		public System.String HotelName { get; set; }
		public System.Int16 NumberOfFloors { get; set; }
	}
}